<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            // ========== TOYOTA ==========
            [
                'brand' => 'Toyota',
                'model' => 'Vios',
                'year' => 2024,
                'car_type' => 'Sedan',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 1000,
                'rfid_type' => 'Easytrip',
                'is_available' => true,
                'is_featured' => true,
                'description' => 'Compact and fuel-efficient sedan perfect for city driving. Easy to park and economical on gas.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Innova',
                'year' => 2023,
                'car_type' => 'SUV',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'seats' => 7,
                'price_per_day' => 1500,
                'rfid_type' => 'Autosweep',
                'is_available' => true,
                'is_featured' => true,
                'description' => 'Spacious family van with diesel engine. Perfect for group travels and long drives.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Hilux',
                'year' => 2024,
                'car_type' => 'Pickup',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 5,
                'price_per_day' => 1600,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Durable pickup truck with powerful diesel engine. Great for off-road and heavy loads.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Fortuner',
                'year' => 2024,
                'car_type' => 'SUV',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 7,
                'price_per_day' => 1500,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Premium midsize SUV with commanding road presence and luxurious interior.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // ========== HONDA ==========
            [
                'brand' => 'Honda',
                'model' => 'Civic',
                'year' => 2023,
                'car_type' => 'Sedan',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 1000,
                'rfid_type' => 'Easytrip',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Sporty compact sedan with sleek design and responsive handling.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Honda',
                'model' => 'CR-V',
                'year' => 2024,
                'car_type' => 'SUV',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 1400,
                'rfid_type' => 'Autosweep',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Popular compact SUV with spacious interior and smooth ride quality.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Honda',
                'model' => 'HR-V',
                'year' => 2023,
                'car_type' => 'SUV',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 1500,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Stylish subcompact crossover with versatile cargo space.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // ========== MITSUBISHI ==========
            [
                'brand' => 'Mitsubishi',
                'model' => 'Mirage',
                'year' => 2024,
                'car_type' => 'Sedan',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 800,
                'rfid_type' => 'Easytrip',
                'is_available' => true,
                'is_featured' => true,
                'description' => 'Economical hatchback perfect for budget-conscious travelers.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Mitsubishi',
                'model' => 'Xpander',
                'year' => 2023,
                'car_type' => 'MPV',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'seats' => 7,
                'price_per_day' => 1200,
                'rfid_type' => 'Autosweep',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Modern MPV with bold design and flexible seating configuration.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Mitsubishi',
                'model' => 'Montero Sport',
                'year' => 2024,
                'car_type' => 'SUV',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 7,
                'price_per_day' => 1500,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => true,
                'description' => 'Powerful SUV with premium features and excellent off-road capability.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // ========== FORD ==========
            [
                'brand' => 'Ford',
                'model' => 'EcoSport',
                'year' => 2023,
                'car_type' => 'Hatchback',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 900,
                'rfid_type' => 'Easytrip',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Compact SUV with elevated driving position and agile handling.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Ford',
                'model' => 'Ranger',
                'year' => 2024,
                'car_type' => 'Pickup',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 5,
                'price_per_day' => 2000,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Tough and capable pickup truck built for work and adventure.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // ========== NISSAN ==========
            [
                'brand' => 'Nissan',
                'model' => 'Almera',
                'year' => 2024,
                'car_type' => 'Sedan',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 1000,
                'rfid_type' => 'Autosweep',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Practical sedan with excellent fuel economy and spacious trunk.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Nissan',
                'model' => 'Navarra',
                'year' => 2023,
                'car_type' => 'Pickup',
                'transmission' => 'Manual',
                'fuel_type' => 'Diesel',
                'seats' => 5,
                'price_per_day' => 2000,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => true,
                'description' => 'Reliable pickup truck with comfortable ride and strong performance.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Nissan',
                'model' => 'Terra',
                'year' => 2024,
                'car_type' => 'SUV',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 7,
                'price_per_day' => 2000,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Sophisticated SUV with premium comfort and advanced safety features.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // ========== SUZUKI ==========
            [
                'brand' => 'Suzuki',
                'model' => 'Swift',
                'year' => 2024,
                'car_type' => 'Hatchback',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 800,
                'rfid_type' => 'Easytrip',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Fun and zippy hatchback with sporty character and low fuel consumption.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Suzuki',
                'model' => 'Ertiga',
                'year' => 2023,
                'car_type' => 'MPV',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'seats' => 7,
                'price_per_day' => 1100,
                'rfid_type' => 'Autosweep',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Affordable MPV with three-row seating perfect for large families.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // ========== ISUZU ==========
            [
                'brand' => 'Isuzu',
                'model' => 'mu-X',
                'year' => 2024,
                'car_type' => 'SUV',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 7,
                'price_per_day' => 2000,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Robust SUV with legendary diesel reliability and commanding view.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // ========== HYUNDAI ==========
            [
                'brand' => 'Hyundai',
                'model' => 'Accent',
                'year' => 2023,
                'car_type' => 'Sedan',
                'transmission' => 'Automatic',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 1000,
                'rfid_type' => 'Easytrip',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Stylish subcompact sedan with modern features and comfortable cabin.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Hyundai',
                'model' => 'Santa Fe',
                'year' => 2024,
                'car_type' => 'SUV',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 7,
                'price_per_day' => 2000,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Premium midsize SUV with upscale interior and advanced technology.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            
            // ========== KIA ==========
            [
                'brand' => 'Kia',
                'model' => 'Sotto',
                'year' => 2023,
                'car_type' => 'Sedan',
                'transmission' => 'Manual',
                'fuel_type' => 'Gasoline',
                'seats' => 5,
                'price_per_day' => 1400,
                'rfid_type' => 'Autosweep',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Practical city car with generous interior space and value-packed features.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'brand' => 'Kia',
                'model' => 'Sorento',
                'year' => 2024,
                'car_type' => 'SUV',
                'transmission' => 'Automatic',
                'fuel_type' => 'Diesel',
                'seats' => 7,
                'price_per_day' => 1600,
                'rfid_type' => 'Both',
                'is_available' => true,
                'is_featured' => false,
                'description' => 'Sophisticated SUV with elegant design and powerful diesel engine.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert all cars
        foreach ($cars as $car) {
            Car::create($car);
        }

        
    }
}
